# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FbMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.CharField(max_length=200)),
                ('meta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FbThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fbmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='fb_parser.FbThread'),
        ),
    ]
