# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_parser', '0002_auto_20170620_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=100)),
                ('threads of user', models.ManyToManyField(to='fb_parser.FbThread')),
            ],
        ),
    ]
